DEMO_TOOL_REGISTRY = [
    {
        "name": "find_data",
        "args": {"query": "string", "limit": "integer?", "public_only": "boolean?", "geography": "string?", "time_range": "string?"},
        "returns": {"ok": "boolean", "data": "discovery result with variables, datasets, reports, sources, organizations"},
        "risk": "read",
        "demo_safe": True,
    },
    {
        "name": "semantic_search",
        "args": {"query": "string", "object_types": "string[]?", "limit": "integer?"},
        "returns": {"ok": "boolean", "data": {"query": "string", "mode": "string", "results": "array"}},
        "risk": "read",
        "demo_safe": True,
    },
    {
        "name": "get_variable_detail",
        "args": {"variable_id": "uuid"},
        "returns": {"ok": "boolean", "data": "report variable detail with report/source/evidence context"},
        "risk": "read",
        "demo_safe": True,
    },
    {
        "name": "get_report_detail",
        "args": {"report_id": "uuid"},
        "returns": {"ok": "boolean", "data": "report detail with source context and variables"},
        "risk": "read",
        "demo_safe": True,
    },
    {
        "name": "get_source_detail",
        "args": {"source_id": "uuid"},
        "returns": {"ok": "boolean", "data": "source detail with linked report/dataset/organization ids"},
        "risk": "read",
        "demo_safe": True,
    },
    {
        "name": "get_organization_detail",
        "args": {"organization_id": "uuid"},
        "returns": {"ok": "boolean", "data": "ecosystem organization detail with source context"},
        "risk": "read",
        "demo_safe": True,
    },
    {
        "name": "compare_concepts",
        "args": {"query_or_concept_id": "string", "report_ids": "uuid[]?"},
        "returns": {"ok": "boolean", "data": {"query_or_concept_id": "string", "comparisons": "array"}},
        "risk": "read",
        "demo_safe": True,
    },
    {
        "name": "list_available_filters",
        "args": {},
        "returns": {"ok": "boolean", "data": {"object_types": "array", "geographies": "array", "availability": "array", "source_types": "array"}},
        "risk": "read",
        "demo_safe": True,
    },
    {
        "name": "job_status",
        "args": {"job_id": "uuid"},
        "returns": {"ok": "boolean", "data": "job status record"},
        "risk": "read",
        "demo_safe": True,
    },
    {
        "name": "submit_feedback",
        "args": {"answer_id": "string?", "result_id": "string?", "feedback_type": "string", "comment": "string?"},
        "returns": {"ok": "boolean", "data": "created feedback record"},
        "risk": "low_write",
        "demo_safe": True,
    },
]

UNSAFE_TOOLS_NOT_EXPOSED = [
    "shell",
    "ingest_excel",
    "process_source",
    "process_report",
    "process_ecosystem_org",
    "resolve_source",
    "generate_codebook",
    "create_extraction_batch",
    "import_extraction_batch",
    "create_review_batch",
    "import_review_batch",
    "build_search_index",
    "embed_search_index",
    "migrate",
    "delete_*",
]
